sonata_admin:
  title: "Sonata Admin"
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
  # security:
  #   handler: sonata.admin.security.handler.acl

  #   # this service MUST implement ``Sonata\AdminBundle\Util\AdminAclUserManagerInterface``.
  #   acl_user_manager: App\Manager\AclUserManager

  #   role_admin: ROLE_USER
  #   role_super_admin: ROLE_SUPER_ADMIN

  #   # acl security information
  #   information:
  #       GUEST:    [VIEW, LIST]
  #       STAFF:    [EDIT, HISTORY, LIST, CREATE]
  #       EDITOR:   [OPERATOR, EXPORT]
  #       ADMIN:    [MASTER]

  #   # permissions not related to an object instance and also to be available when objects do not exist
  #   # the DELETE admin permission means the user is allowed to batch delete objects
  #   admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

  #   # permission related to the objects
  #   object_permissions: [VIEW, EDIT, HISTORY, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]


sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]
